export type CatalogProduct = {
  id: string;
  name: string;
  category: string;
  categoryId: string;
  sort: string;
  description: string;
  image: string;
  price: number;
};

export const catalogProducts: CatalogProduct[] = [
  {
    id: "bile-vyno-shato-de-win",
    name: "Шато де Він",
    category: "Білі вина",
    categoryId: "weisswein",
    sort: "Напівсолодке",
    description: " насичений, помірно кислий, з м'якими нотами фруктів та легким шлейфом ванілі у післясмаку.",
    image: "/images/bile-vyno.jpg",
    price: 8000,
  },
  {
    id: "bile-vyno-alzanska-dolina",
    name: "Алазанська долина",
    category: "Білі вина",
    categoryId: "weisswein",
    sort: "Напівсолодке",
    description: "Зелене яблуко, груша, білий виноград, цитрус.",
    image: "/images/bile-vyno.jpg",
    price: 8500,
  },
  {
    id: "bile-vyno-la-perla-bianko",
    name: "Ла Перла Б'янко",
    category: "Білі вина",
    categoryId: "weisswein",
    sort: "Напівсолодке",
    description: "Персик, абрикос, білі квіти, медові відтінки.",
    image: "/images/bile-vyno.jpg",
    price: 7500,
  },
  {
    id: "bile-vyno-shardonay",
    name: "Шардоне",
    category: "Білі вина",
    categoryId: "weisswein",
    sort: "Сухе",
    description: "Яблуко, цитрус, вершковість, трохи ванілі.",
    image: "/images/bile-vyno.jpg",
    price: 8500,
  },
  {
    id: "bile-vyno-bila-orhideya",
    name: "Біла орхідея",
    category: "Білі вина",
    categoryId: "weisswein",
    sort: "Напівсолодке",
    description: "Білі квіти, груша, абрикос, мед.",
    image: "/images/bile-vyno.jpg",
    price: 7500,
  },
  {
    id: "bile-vyno-videnskyy-vals",
    name: "Віденський вальс",
    category: "Білі вина",
    categoryId: "weisswein",
    sort: "Напівсолодке",
    description: "Мигдаль, білий персик, квітковий аромат.",
    image: "/images/bile-vyno.jpg",
    price: 7500,
  },
  {
    id: "bile-vyno-ayva",
    name: "Айва",
    category: "Білі вина",
    categoryId: "weisswein",
    sort: "Напівсолодке",
    description: "Айва, яблуко, груша, легка свіжість.",
    image: "/images/bile-vyno.jpg",
    price: 8000,
  },
  {
    id: "bile-vyno-shato-royal",
    name: "Шато де Рояль",
    category: "Білі вина",
    categoryId: "weisswein",
    sort: "Напівсолодке",
    description: "Світлий відтінок, легкий фруктовий аромат із тонами білого винограду та персика.",
    image: "/images/bile-vyno.jpg",
    price: 8000,
  },
  {
    id: "krasne-vino-alzanska-dolina",
    name: "Алазанська долина",
    category: "Червоні вина",
    categoryId: "rotwein",
    sort: "Напівсолодке",
    description: "Вишня, слива, чорна смородина.",
    image: "/images/fon-red-wine.png",
    price: 8500,
  },
  {
    id: "krasne-vino-valensiya-smorodina",
    name: "Валенсія Смородина",
    category: "Червоні вина",
    categoryId: "rotwein",
    sort: "Напівсолодке",
    description: "Смородина, полуниця, стиглі ягоди.",
    image: "/images/fon-red-wine.png",
    price: 7500,
  },
  {
    id: "krasne-vino-dika-cherezha",
    name: "Дика черешня",
    category: "Червоні вина",
    categoryId: "rotwein",
    sort: "Напівсолодке",
    description: "Черешня, вишня, ягідне варення.",
    image: "/images/fon-red-wine2.png ",
    price: 8000,
  },
  {
    id: "krasne-vino-odeskyi-chorniy",
    name: "Одеський чорний",
    category: "Червоні вина",
    categoryId: "rotwein",
    sort: "Сухе",
    description: "Чорнослив, ожина, спеції, шоколад.",
    image: "/images/fon-red-wine.png",
    price: 8500,
  },
  {
    id: "krasne-vino-kaberne-elitne",
    name: "Каберне Елітне",
    category: "Червоні вина",
    categoryId: "rotwein",
    sort: "Сухе",
    description: "Чорна смородина, дуб, шоколад, вишня.",
    image: "/images/fon-red-wine2.png",
    price: 8500,
  },
  {
    id: "krasne-vino-rubino-grande",
    name: "Рубіно Гранде",
    category: "Червоні вина",
    categoryId: "rotwein",
    sort: "Напівсолодке",
    description: "Ожина, слива, чорна смородина.",
    image: "/images/fon-red-wine.png",
    price: 7500,
  },
  {
    id: "krasne-vino-ridniy-krai",
    name: "Рідний край",
    category: "Червоні вина",
    categoryId: "rotwein",
    sort: "Напівсолодке",
    description: "Вишня, чорні ягоди, м’які таніни.",
    image: "/images/fon-red-wine.png",
    price: 7500,
  },
  {
    id: "krasne-vino-ah-nuar",
    name: "Ах Нуар",
    category: "Червоні вина",
    categoryId: "rotwein",
    sort: "Напівсолодке",
    description: "Малина, ожина, чорниця.",
    image: "/images/fon-red-wine2.png",
    price: 7500,
  },
  {
    id: "krasne-vino-matador",
    name: "Матадор",
    category: "Червоні вина",
    categoryId: "rotwein",
    sort: "Напівсухе",
    description: "Смородина, чорниця, спеції.",
    image: "/images/fon-red-wine.png",
    price: 7500,
  },
  {
    id: "krasne-vino-bastard",
    name: "Бастардо",
    category: "Червоні вина",
    categoryId: "rotwein",
    sort: "Солодке",
    description: "Чорнослив, спеції, бархатистий смак.",
    image: "/images/fon-red-wine.png",
    price: 8000,
  },
  {
    id: "krasne-vino-izabella",
    name: "Ізабелла",
    category: "Червоні вина",
    categoryId: "rotwein",
    sort: "Напівсолодке",
    description: "Полуниця, клубника, виноград Ізабелла.",
    image: "/images/fon-red-wine2.png",
    price: 7000,
  },
  {
    id: "krasne-vino-glintvein",
    name: "Глінтвейн",
    category: "Червоні вина",
    categoryId: "rotwein",
    sort: "Напівсолодке",
    description: "Кориця, гвоздика, апельсин, червоні ягоди.",
    image: "/images/fon-red-wine2.png",
    price: 8500,
  },
  {
    id: "krasne-vino-vermut-fratelli-amaretto",
    name: "Вермут Fratelli Amaretto",
    category: "Червоні вина",
    categoryId: "rotwein",
    sort: "Десертне",
    description: "Амаретто, мигдаль, вишня, полуниця, ваніль.",
    image: "/images/fon-red-wine2.png",
    price: 8500,
  },
  {
    id: "roze-vino-knyazhnya-lidiya",
    name: "Княгиня Лідія",
    category: "Рожеві вина",
    categoryId: "rose",
    sort: "Полусладкое",
    description: "Лічі, пелюстки троянди, полуниця, малина.",
    image: "/images/roze-vino.jpg",
    price: 7500,
  },
  {
    id: "roze-vino-chornomorska-perlyna",
    name: "Чорноморська перлина",
    category: "Рожеві вина",
    categoryId: "rose",
    sort: "Напівсолодке",
    description: "Полуниця, малина, персик, квітковий аромат.",
    image: "/images/roze-vino.jpg",
    price: 7500,
  },
  {
    id: "igriste-vino-brut",
    name: "Ігристе вино Brut",
    category: "Ігристі вина",
    categoryId: "schaumwein",
    sort: "Brut",
    description: "Ніжна перлівка, свіжість і святковий настрій у кожній келиху.",
    image: "/images/igriste-vino.jpg",
    price: 1499,
  },
  {
    id: "igriste-vino-demisec",
    name: "Ігристе вино Demi-Sec",
    category: "Ігристі вина",
    categoryId: "schaumwein",
    sort: "Demi-Sec",
    description: "Напівсухе ігристе вино з м’якою фруктовістю.",
    image: "/images/igriste-vino.jpg",
    price: 1599,
  },
  {
    id: "marengo-brut-075",
    name: "Marengo Brut, 0,75 л",
    category: "Ігристі вина · пляшка",
    categoryId: "schaumwein",
    sort: "Брют",
    description: "Свіже біле ігристе з делікатними квітковими нотами та чистим сухим післясмаком.",
    image: "/images/bottled/marengo-brut.webp",
    price: 16400,
  },
  {
    id: "marengo-pinot-grigio-brut-075",
    name: "Marengo Pinot Grigio Brut, 0,75 л",
    category: "Ігристі вина · пляшка",
    categoryId: "schaumwein",
    sort: "Брют",
    description: "Білі ягоди, легкий квітковий аромат і освіжаючий сухий смак.",
    image: "/images/bottled/marengo-pinot-grigio-brut.webp",
    price: 16400,
  },
  {
    id: "marengo-chardonnay-semi-dry-075",
    name: "Marengo Chardonnay, 0,75 л",
    category: "Ігристі вина · пляшка",
    categoryId: "schaumwein",
    sort: "Напівсухе",
    description: "М’яке ігристе Chardonnay з фруктовими та цитрусовими відтінками.",
    image: "/images/bottled/marengo-chardonnay-semi-dry.webp",
    price: 16400,
  },
  {
    id: "marengo-sweet-bianco-075",
    name: "Marengo Sweet Bianco, 0,75 л",
    category: "Ігристі вина · пляшка",
    categoryId: "schaumwein",
    sort: "Солодке",
    description: "Ароматне солодке ігристе з квітково-фруктовим смаком і ніжними бульбашками.",
    image: "/images/bottled/marengo-sweet-bianco.webp",
    price: 16400,
  },
  {
    id: "marengo-bellini-075",
    name: "Marengo Bellini, 0,75 л",
    category: "Ігристі вина · пляшка",
    categoryId: "schaumwein",
    sort: "Солодке",
    description: "Яскравий персиковий смак, легка фруктова солодкість і святкова ігристість.",
    image: "/images/bottled/marengo-bellini.webp",
    price: 18000,
  },
  {
    id: "marengo-moscato-075",
    name: "Marengo Moscato, 0,75 л",
    category: "Ігристі вина · пляшка",
    categoryId: "schaumwein",
    sort: "Напівсолодке",
    description: "Виразний мускатний аромат, квіткові ноти та м’який фруктовий післясмак.",
    image: "/images/bottled/marengo-moscato.webp",
    price: 18900,
  },
  {
    id: "marengo-semi-sweet-rose-075",
    name: "Marengo Semi-Sweet Rosé, 0,75 л",
    category: "Ігристі вина · пляшка",
    categoryId: "schaumwein",
    sort: "Рожеве напівсолодке",
    description: "Ніжне рожеве ігристе з ароматом червоних ягід і м’якою солодкістю.",
    image: "/images/bottled/marengo-semi-sweet-rose.webp",
    price: 18900,
  },
  {
    id: "marengo-semi-sweet-bianco-075",
    name: "Marengo Semi-Sweet Bianco, 0,75 л",
    category: "Ігристі вина · пляшка",
    categoryId: "schaumwein",
    sort: "Напівсолодке",
    description: "Гармонійне біле ігристе з фруктовим ароматом і збалансованою солодкістю.",
    image: "/images/bottled/marengo-semi-sweet-bianco.webp",
    price: 18900,
  },
  {
    id: "chacha-classic",
    name: "Чача Classic",
    category: "Спиртні напої",
    categoryId: "spirituosen",
    sort: "Classic",
    description: "Традиційна спеціальність з яскравим характером і глибоким смаком.",
    image: "/images/chacha.jpg",
    price: 1899,
  },
  {
    id: "konjak-classic",
    name: "Коньяк Classic",
    category: "Спиртні напої",
    categoryId: "spirituosen",
    sort: "Classic",
    description: "Елегантний, теплий і м’який у фіналі напій для особливих моментів.",
    image: "/images/konjak.jpg",
    price: 2499,
  },
  {
    id: "rom-classic",
    name: "Ром Classic",
    category: "Спиртні напої",
    categoryId: "spirituosen",
    sort: "Classic",
    description: "Солодкувата пряність з глибиною і приємним ароматом.",
    image: "/images/rom.jpg",
    price: 2199,
  },
  {
    id: "koblevo-classic-brandy-05",
    name: "KOBLEVO Classic Brandy, 0,5 л",
    category: "Коньяки та бренді · пляшка",
    categoryId: "brandy",
    sort: "Ординарний",
    description: "М’який український бренді з нотами ванілі, волоського горіха та дуба.",
    image: "/images/bottled/koblevo-classic-brandy.webp",
    price: 11800,
  },
  {
    id: "brandson-classic-05",
    name: "Brandson Classic, 0,5 л",
    category: "Коньяки та бренді · пляшка",
    categoryId: "brandy",
    sort: "Ординарний · 36%",
    description: "Збалансований бренді з теплими горіховими, ванільними та дубовими відтінками.",
    image: "/images/bottled/brandson-classic.webp",
    price: 16400,
  },
  {
    id: "koblevo-selection-vs-05",
    name: "KOBLEVO Selection V.S., 0,5 л",
    category: "Коньяки та бренді · пляшка",
    categoryId: "brandy",
    sort: "V.S. · 3 роки",
    description: "Трилітній коньяк України з карамельними, фруктовими та дубовими нотами.",
    image: "/images/bottled/koblevo-selection-vs.webp",
    price: 19300,
  },
  {
    id: "koblevo-grand-vs-05",
    name: "KOBLEVO Grand V.S., 0,5 л",
    category: "Коньяки та бренді · пляшка",
    categoryId: "brandy",
    sort: "V.S. · 3 роки",
    description: "Квітковий аромат, ваніль, горіх і м’які дубові ноти у теплому післясмаку.",
    image: "/images/bottled/koblevo-grand-vs.webp",
    price: 19400,
  },
  {
    id: "koblevo-mykolaiv-vsop-05",
    name: "KOBLEVO Миколаїв нескорений V.S.O.P., 0,5 л",
    category: "Коньяки та бренді · пляшка",
    categoryId: "brandy",
    sort: "V.S.O.P. · 4 роки",
    description: "Витриманий український коньяк із медовими нотами, сухофруктами та ваніллю.",
    image: "/images/bottled/koblevo-mykolaiv-vsop.webp",
    price: 21000,
  },
  {
    id: "koblevo-grand-reserve-vsop-05",
    name: "KOBLEVO Grand Reserve V.S.O.P., 0,5 л",
    category: "Коньяки та бренді · пляшка",
    categoryId: "brandy",
    sort: "V.S.O.P. · 5 років",
    description: "Сухофрукти, лісовий горіх, ваніль і темний шоколад у тривалому післясмаку.",
    image: "/images/bottled/koblevo-grand-reserve-vsop.webp",
    price: 23300,
  },
  {
    id: "koblevo-chardonnay-bottle",
    name: "KOBLEVO Chardonnay, 0,75 л",
    category: "Білі вина · пляшка",
    categoryId: "weisswein",
    sort: "Сухе",
    description: "Свіже біле сухе вино з фруктовими нотами та м’яким чистим післясмаком.",
    image: "/images/bottled/koblevo-chardonnay.webp",
    price: 10500,
  },
  {
    id: "koblevo-vilna-ptashka-bottle",
    name: "KOBLEVO Вільна пташка, 0,75 л",
    category: "Білі вина · пляшка",
    categoryId: "weisswein",
    sort: "Сухе",
    description: "Легке біле сухе вино з делікатною фруктовістю та освіжаючою кислотністю.",
    image: "/images/bottled/koblevo-vilna-ptashka.webp",
    price: 10500,
  },
  {
    id: "koblevo-mriia-bottle",
    name: "KOBLEVO Мрія, 0,75 л",
    category: "Білі вина · пляшка",
    categoryId: "weisswein",
    sort: "Напівсолодке",
    description: "Білі квіти, легкі мускатні відтінки та м’який пряний післясмак.",
    image: "/images/bottled/koblevo-mriia.webp",
    price: 11500,
  },
  {
    id: "koblevo-muscat-bottle",
    name: "KOBLEVO Muscat, 0,75 л",
    category: "Білі вина · пляшка",
    categoryId: "weisswein",
    sort: "Напівсолодке",
    description: "Аромат цитрона й пелюсток чайної троянди, округлий та гармонійний смак.",
    image: "/images/bottled/koblevo-muscat.webp",
    price: 11500,
  },
  {
    id: "koblevo-exclusive-chardonnay-bottle",
    name: "KOBLEVO Exclusive Chardonnay, 0,75 л",
    category: "Білі вина · пляшка",
    categoryId: "weisswein",
    sort: "Сухе",
    description: "Білі екзотичні фрукти та зелене яблуко у свіжому збалансованому смаку.",
    image: "/images/bottled/koblevo-exclusive-chardonnay.webp",
    price: 14400,
  },
  {
    id: "koblevo-exclusive-pinot-grigio-bottle",
    name: "KOBLEVO Exclusive Pinot Grigio, 0,75 л",
    category: "Білі вина · пляшка",
    categoryId: "weisswein",
    sort: "Сухе",
    description: "Квіткові ноти, білі ягоди та легкий освіжаючий смак.",
    image: "/images/bottled/koblevo-exclusive-pinot-grigio.webp",
    price: 14400,
  },
  {
    id: "koblevo-kleopatra-bottle",
    name: "KOBLEVO Kleopatra, 0,75 л",
    category: "Білі вина · пляшка",
    categoryId: "weisswein",
    sort: "Кріплене",
    description: "Насичене біле кріплене вино з виразним ароматом і теплим післясмаком.",
    image: "/images/bottled/koblevo-kleopatra.webp",
    price: 15100,
  },
  {
    id: "koblevo-muscat-gold-bottle",
    name: "KOBLEVO Muscat Gold, 0,75 л",
    category: "Білі вина · пляшка",
    categoryId: "weisswein",
    sort: "Десертне кріплене",
    description: "Сухофрукти, пелюстки чайної троянди та насичений мускатний аромат.",
    image: "/images/bottled/koblevo-muscat-gold.webp",
    price: 15100,
  },
  {
    id: "koblevo-red-kalyna-bottle",
    name: "KOBLEVO Моя червона калина, 0,75 л",
    category: "Червоні вина · пляшка",
    categoryId: "rotwein",
    sort: "Сухе",
    description: "Сухе червоне вино з ягідним характером, легкою терпкістю та чистим фіналом.",
    image: "/images/bottled/koblevo-red-kalyna.webp",
    price: 10500,
  },
  {
    id: "koblevo-saperavi-bottle",
    name: "KOBLEVO Saperavi, 0,75 л",
    category: "Червоні вина · пляшка",
    categoryId: "rotwein",
    sort: "Сухе",
    description: "Насичене червоне сухе вино з темними ягодами та приємною терпкістю.",
    image: "/images/bottled/koblevo-saperavi.webp",
    price: 11500,
  },
  {
    id: "koblevo-stefaniia-bottle",
    name: "KOBLEVO Стефанія, 0,75 л",
    category: "Червоні вина · пляшка",
    categoryId: "rotwein",
    sort: "Напівсолодке",
    description: "М’яке червоне напівсолодке вино зі стиглими ягодами та округлим смаком.",
    image: "/images/bottled/koblevo-stefaniia.webp",
    price: 11500,
  },
  {
    id: "koblevo-bastardo-bottle",
    name: "KOBLEVO Bastardo, 0,75 л",
    category: "Червоні вина · пляшка",
    categoryId: "rotwein",
    sort: "Напівсолодке",
    description: "Червона слива, шоколадні відтінки та м’який оксамитовий післясмак.",
    image: "/images/bottled/koblevo-bastardo.webp",
    price: 11500,
  },
  {
    id: "koblevo-odeskyi-chornyi-bottle",
    name: "KOBLEVO Одеський чорний, 0,75 л",
    category: "Червоні вина · пляшка",
    categoryId: "rotwein",
    sort: "Напівсолодке",
    description: "Темні ягоди, легкі прянощі та насичений гармонійний смак.",
    image: "/images/bottled/koblevo-odeskyi-chornyi.webp",
    price: 11500,
  },
  {
    id: "koblevo-cabernet-bottle",
    name: "KOBLEVO Cabernet, 0,75 л",
    category: "Червоні вина · пляшка",
    categoryId: "rotwein",
    sort: "Сухе",
    description: "Чорна смородина, вишня та легкі пряні ноти у сухому вині.",
    image: "/images/bottled/koblevo-cabernet.webp",
    price: 12500,
  },
  {
    id: "koblevo-exclusive-merlot-bottle",
    name: "KOBLEVO Exclusive Merlot, 0,75 л",
    category: "Червоні вина · пляшка",
    categoryId: "rotwein",
    sort: "Сухе",
    description: "Чорниця, шовковиця, солодкі спеції та помірні таніни.",
    image: "/images/bottled/koblevo-exclusive-merlot.webp",
    price: 14400,
  },
  {
    id: "koblevo-exclusive-cabernet-bottle",
    name: "KOBLEVO Exclusive Cabernet, 0,75 л",
    category: "Червоні вина · пляшка",
    categoryId: "rotwein",
    sort: "Сухе",
    description: "Насичений ягідний аромат, благородна терпкість і тривалий післясмак.",
    image: "/images/bottled/koblevo-exclusive-cabernet.webp",
    price: 14400,
  },
  {
    id: "koblevo-bakkara-bottle",
    name: "KOBLEVO Bakkara, 0,75 л",
    category: "Червоні вина · пляшка",
    categoryId: "rotwein",
    sort: "Кріплене",
    description: "Чорнослив, чорна смородина й шоколад у насиченому кріпленому вині.",
    image: "/images/bottled/koblevo-bakkara.webp",
    price: 14800,
  },
  {
    id: "koblevo-kagor-ukrainskyi-bottle",
    name: "KOBLEVO Кагор Український, 0,75 л",
    category: "Червоні вина · пляшка",
    categoryId: "rotwein",
    sort: "Десертне",
    description: "Глибокий рубіновий колір, стиглі темні ягоди та солодкий оксамитовий смак.",
    image: "/images/bottled/koblevo-kagor-ukrainskyi.webp",
    price: 15100,
  },
  {
    id: "koblevo-muscat-rose-bottle",
    name: "KOBLEVO Muscat Rose, 0,75 л",
    category: "Рожеві вина · пляшка",
    categoryId: "rose",
    sort: "Напівсолодке",
    description: "Пелюстки чайної троянди, солодкі спеції та ніжний ароматний післясмак.",
    image: "/images/bottled/koblevo-muscat-rose.webp",
    price: 11500,
  },
  {
    id: "marengo-bianco-05",
    name: "Marengo Bianco, 0,5 л",
    category: "Вермути та коктейлі · пляшка",
    categoryId: "vermouth",
    sort: "Білий вермут",
    description: "Легкий ароматний білий вермут для подачі охолодженим або у коктейлях.",
    image: "/images/bottled/marengo-bianco-05.webp",
    price: 10500,
  },
  {
    id: "marengo-mojito-05",
    name: "Marengo Mojito, 0,5 л",
    category: "Вермути та коктейлі · пляшка",
    categoryId: "vermouth",
    sort: "Аперитив",
    description: "Лайм, лимон, м’ята, імбир і трави зі свіжим м’ятно-цитрусовим фіналом.",
    image: "/images/bottled/marengo-mojito-05.webp",
    price: 12400,
  },
  {
    id: "marengo-bianco-1l",
    name: "Marengo Bianco, 1 л",
    category: "Вермути та коктейлі · пляшка",
    categoryId: "vermouth",
    sort: "Білий вермут",
    description: "Ароматний білий вермут із м’яким трав’яним характером, 1 літр.",
    image: "/images/bottled/marengo-bianco-1l.webp",
    price: 17000,
  },
  {
    id: "marengo-hawaii-1l",
    name: "Marengo Hawaii, 1 л",
    category: "Вермути та коктейлі · пляшка",
    categoryId: "vermouth",
    sort: "Аперитив",
    description: "Яскравий тропічний аперитив із фруктовим ароматом, 1 літр.",
    image: "/images/bottled/marengo-hawaii-1l.webp",
    price: 17000,
  },
  {
    id: "marengo-mojito-1l",
    name: "Marengo Mojito, 1 л",
    category: "Вермути та коктейлі · пляшка",
    categoryId: "vermouth",
    sort: "Аперитив",
    description: "Освіжаюче поєднання лайма, лимона, м’яти, імбиру й ароматних трав.",
    image: "/images/bottled/marengo-mojito-1l.webp",
    price: 21400,
  },
  {
    id: "marengo-pina-colada-1l",
    name: "Marengo Piña Colada, 1 л",
    category: "Вермути та коктейлі · пляшка",
    categoryId: "vermouth",
    sort: "Аперитив",
    description: "Тропічний ананасовий смак із м’якими вершковими відтінками, 1 літр.",
    image: "/images/bottled/marengo-pina-colada-1l.webp",
    price: 21400,
  },
  {
    id: "marengo-rosso-1l",
    name: "Marengo Rosso, 1 л",
    category: "Вермути та коктейлі · пляшка",
    categoryId: "vermouth",
    sort: "Червоний вермут",
    description: "Червоний вермут із виразним пряно-трав’яним ароматом і м’яким солодким смаком.",
    image: "/images/bottled/marengo-rosso-1l.webp",
    price: 23200,
  },
];

export function getCatalogProductById(id: string) {
  return catalogProducts.find((product) => product.id === id) ?? null;
}

export function getCatalogProductsForCategory(categoryId: string) {
  return catalogProducts.filter((product) => product.categoryId === categoryId);
}
