export type CatalogProduct = {
  id: string;
  name: string;
  category: string;
  categoryId: string;
  sort: string;
  description: string;
  image: string;
  price: number;
};

export const catalogProducts: CatalogProduct[] = [
  {
    id: "bile-vyno-shato-de-win ",
    name: "Шато де він",
    category: "Білі вина",
    categoryId: "weisswein",
    sort: "Напівсолодке",
    description: " насичений, помірно кислий, з м'якими нотами фруктів та легким шлейфом ванілі у післясмаку.",
    image: "/images/bile-vyno.jpg",
    price: 8000,
  },
  {
    id: "bile-vyno-alzanska-dolina",
    name: "Алазанська долина",
    category: "Білі вина",
    categoryId: "weisswein",
    sort: "Напівсолодке",
    description: "Зелене яблуко, груша, білий виноград, цитрус.",
    image: "/images/bile-vyno.jpg",
    price: 8500,
  },
  {
    id: "bile-vyno-la-perla-bianko",
    name: "Ла Перла Б'янко",
    category: "Білі вина",
    categoryId: "weisswein",
    sort: "Напівсолодке",
    description: "Персик, абрикос, білі квіти, медові відтінки.",
    image: "/images/bile-vyno.jpg",
    price: 7500,
  },
  {
    id: "bile-vyno-shardonay",
    name: "Шардоне",
    category: "Білі вина",
    categoryId: "weisswein",
    sort: "Сухе",
    description: "Яблуко, цитрус, вершковість, трохи ванілі.",
    image: "/images/bile-vyno.jpg",
    price: 8500,
  },
  {
    id: "bile-vyno-bila-orhideya",
    name: "Біла орхідея",
    category: "Білі вина",
    categoryId: "weisswein",
    sort: "Напівсолодке",
    description: "Білі квіти, груша, абрикос, мед.",
    image: "/images/bile-vyno.jpg",
    price: 7500,
  },
  {
    id: "bile-vyno-videnskyy-vals",
    name: "Віденський вальс",
    category: "Білі вина",
    categoryId: "weisswein",
    sort: "Напівсолодке",
    description: "Мигдаль, білий персик, квітковий аромат.",
    image: "/images/bile-vyno.jpg",
    price: 7500,
  },
  {
    id: "bile-vyno-ayva",
    name: "Айва",
    category: "Білі вина",
    categoryId: "weisswein",
    sort: "Напівсолодке",
    description: "Айва, яблуко, груша, легка свіжість.",
    image: "/images/bile-vyno.jpg",
    price: 8000,
  },
  {
    id: "bile-vyno-shato-royal",
    name: "Шато де Рояль",
    category: "Білі вина",
    categoryId: "weisswein",
    sort: "Напівсолодке",
    description: "Світлий відтінок, легкий фруктовий аромат із тонами білого винограду та персика.",
    image: "/images/bile-vyno.jpg",
    price: 8000,
  },
  {
    id: "krasne-vino-alzanska-dolina",
    name: "Алазанська долина",
    category: "Червоні вина",
    categoryId: "rotwein",
    sort: "Напівсолодке",
    description: "Вишня, слива, чорна смородина.",
    image: "/images/krasne-vino.jpg",
    price: 8500,
  },
  {
    id: "krasne-vino-valensiya-smorodina",
    name: "Валенсія Смородина",
    category: "Червоні вина",
    categoryId: "rotwein",
    sort: "Напівсолодке",
    description: "Смородина, полуниця, стиглі ягоди.",
    image: "/images/krasne-vino.jpg",
    price: 7500,
  },
  {
    id: "krasne-vino-dika-cherezha",
    name: "Дика черешня",
    category: "Червоні вина",
    categoryId: "rotwein",
    sort: "Напівсолодке",
    description: "Черешня, вишня, ягідне варення.",
    image: "/images/krasne-vino.jpg",
    price: 8000,
  },
  {
    id: "krasne-vino-odeskyi-chorniy",
    name: "Одеський чорний",
    category: "Червоні вина",
    categoryId: "rotwein",
    sort: "Сухе",
    description: "Чорнослив, ожина, спеції, шоколад.",
    image: "/images/krasne-vino.jpg",
    price: 8500,
  },
  {
    id: "krasne-vino-kaberne-elitne",
    name: "Каберне Елітне",
    category: "Червоні вина",
    categoryId: "rotwein",
    sort: "Сухе",
    description: "Чорна смородина, дуб, шоколад, вишня.",
    image: "/images/krasne-vino.jpg",
    price: 8500,
  },
  {
    id: "krasne-vino-rubino-grande",
    name: "Рубіно Гранде",
    category: "Червоні вина",
    categoryId: "rotwein",
    sort: "Напівсолодке",
    description: "Ожина, слива, чорна смородина.",
    image: "/images/krasne-vino.jpg",
    price: 7500,
  },
  {
    id: "krasne-vino-ridniy-krai",
    name: "Рідний край",
    category: "Червоні вина",
    categoryId: "rotwein",
    sort: "Напівсолодке",
    description: "Вишня, чорні ягоди, м’які таніни.",
    image: "/images/krasne-vino.jpg",
    price: 7500,
  },
  {
    id: "krasne-vino-ah-nuar",
    name: "Ах Нуар",
    category: "Червоні вина",
    categoryId: "rotwein",
    sort: "Напівсолодке",
    description: "Малина, ожина, чорниця.",
    image: "/images/krasne-vino.jpg",
    price: 7500,
  },
  {
    id: "krasne-vino-matador",
    name: "Матадор",
    category: "Червоні вина",
    categoryId: "rotwein",
    sort: "Напівсухе",
    description: "Смородина, чорниця, спеції.",
    image: "/images/krasne-vino.jpg",
    price: 7500,
  },
  {
    id: "krasne-vino-bastard",
    name: "Бастардо",
    category: "Червоні вина",
    categoryId: "rotwein",
    sort: "Солодке",
    description: "Чорнослив, спеції, бархатистий смак.",
    image: "/images/krasne-vino.jpg",
    price: 8000,
  },
  {
    id: "krasne-vino-izabella",
    name: "Ізабелла",
    category: "Червоні вина",
    categoryId: "rotwein",
    sort: "Напівсолодке",
    description: "Полуниця, клубника, виноград Ізабелла.",
    image: "/images/krasne-vino.jpg",
    price: 7000,
  },
  {
    id: "krasne-vino-glintvein",
    name: "Глінтвейн",
    category: "Червоні вина",
    categoryId: "rotwein",
    sort: "Напівсолодке",
    description: "Кориця, гвоздика, апельсин, червоні ягоди.",
    image: "/images/krasne-vino.jpg",
    price: 8500,
  },
  {
    id: "krasne-vino-vermut-fratelli-amaretto",
    name: "Вермут Fratelli Amaretto",
    category: "Червоні вина",
    categoryId: "rotwein",
    sort: "Десертне",
    description: "Амаретто, мигдаль, вишня, полуниця, ваніль.",
    image: "/images/krasne-vino.jpg",
    price: 8500,
  },
  {
    id: "roze-vino-knyazhnya-lidiya",
    name: "Княгиня Лідія",
    category: "Рожеві вина",
    categoryId: "rose",
    sort: "Полусладкое",
    description: "Лічі, пелюстки троянди, полуниця, малина.",
    image: "/images/roze-vino.jpg",
    price: 7500,
  },
  {
    id: "roze-vino-chornomorska-perlyna",
    name: "Чорноморська перлина",
    category: "Рожеві вина",
    categoryId: "rose",
    sort: "Напівсолодке",
    description: "Полуниця, малина, персик, квітковий аромат.",
    image: "/images/roze-vino.jpg",
    price: 7500,
  },
  {
    id: "igriste-vino-brut",
    name: "Ігристе вино Brut",
    category: "Ігристі вина",
    categoryId: "schaumwein",
    sort: "Brut",
    description: "Ніжна перлівка, свіжість і святковий настрій у кожній келиху.",
    image: "/images/igriste-vino.jpg",
    price: 1499,
  },
  {
    id: "igriste-vino-demisec",
    name: "Ігристе вино Demi-Sec",
    category: "Ігристі вина",
    categoryId: "schaumwein",
    sort: "Demi-Sec",
    description: "Напівсухе ігристе вино з м’якою фруктовістю.",
    image: "/images/igriste-vino.jpg",
    price: 1599,
  },
  {
    id: "chacha-classic",
    name: "Чача Classic",
    category: "Спиртні напої",
    categoryId: "spirituosen",
    sort: "Classic",
    description: "Традиційна спеціальність з яскравим характером і глибоким смаком.",
    image: "/images/chacha.jpg",
    price: 1899,
  },
  {
    id: "konjak-classic",
    name: "Коньяк Classic",
    category: "Спиртні напої",
    categoryId: "spirituosen",
    sort: "Classic",
    description: "Елегантний, теплий і м’який у фіналі напій для особливих моментів.",
    image: "/images/konjak.jpg",
    price: 2499,
  },
  {
    id: "rom-classic",
    name: "Ром Classic",
    category: "Спиртні напої",
    categoryId: "spirituosen",
    sort: "Classic",
    description: "Солодкувата пряність з глибиною і приємним ароматом.",
    image: "/images/rom.jpg",
    price: 2199,
  },
];

export function getCatalogProductById(id: string) {
  return catalogProducts.find((product) => product.id === id) ?? null;
}

export function getCatalogProductsForCategory(categoryId: string) {
  return catalogProducts.filter((product) => product.categoryId === categoryId);
}
